version: '3'

services:
  kakimail:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      #need to ask oracle to not block this port
      - "7777:25"
      - "587:587"
